-- https://www.mockaroo.com/
insert into clients (id, nom, email, date_naissance, titre) values (next value for seq, 'Wanda Gray', 'wgray0@ebay.co.uk', date '1988-07-26', 2);
insert into clients (id, nom, email, date_naissance, titre) values (next value for seq, 'Lisa Mcdonald', 'lmcdonald1@de.vu', date '1952-06-04', 2);
insert into clients (id, nom, email, date_naissance, titre) values (next value for seq, 'Barbara Kim', 'bkim2@deviantart.com', date '1958-07-31', 2);
insert into clients (id, nom, email, date_naissance, titre) values (next value for seq, 'Kevin Sims', 'ksims3@usatoday.com', date '1986-06-03', 1);
insert into clients (id, nom, email, date_naissance, titre) values (next value for seq, 'Phyllis Johnson', 'pjohnson4@ovh.net', date '1980-10-07', 2);
insert into clients (id, nom, email, date_naissance, titre) values (next value for seq, 'Annie Gutierrez', 'agutierrez5@msu.edu', date '1954-02-02', 2);
insert into clients (id, nom, email, date_naissance, titre) values (next value for seq, 'William Day', 'wday6@squarespace.com', date '1960-05-15', 1);
insert into clients (id, nom, email, date_naissance, titre) values (next value for seq, 'Cheryl Woods', 'cwoods7@storify.com', date '1981-04-08', 2);
insert into clients (id, nom, email, date_naissance, titre) values (next value for seq, 'Richard Cox', 'rcox8@dailymotion.com', date '1996-04-25', 1);
insert into clients (id, nom, email, date_naissance, titre) values (next value for seq, 'Bobby Morris', 'bmorris9@intel.com', date '1990-03-30', 1);

insert into roles (id, libelle) values (1, 'Serveurs');
insert into roles (id, libelle) values (2, 'Responsables');

insert into employes (id, nom, idrole) values (1, 'Katherine Peters', 1);
insert into employes (id, nom, idrole) values (2, 'Jimmy Simmons', 1);
insert into employes (id, nom, idrole) values (3, 'Annie Diaz', 2);

insert into cocktails (id, nom) values (next value for seq, 'Mojito');
insert into cocktails (id, nom) values (next value for seq, 'Piña Colada');
insert into cocktails (id, nom) values (next value for seq, 'Margarita');
insert into cocktails (id, nom) values (next value for seq, 'Sex on the beach');
insert into cocktails (id, nom) values (next value for seq, 'Caipirinha');
insert into cocktails (id, nom) values (next value for seq, 'Cosmopolitan');
insert into cocktails (id, nom) values (next value for seq, 'Blue Lagoon');
insert into cocktails (id, nom) values (next value for seq, 'Tequila Sunrise');
insert into cocktails (id, nom) values (next value for seq, 'Punch');
insert into cocktails (id, nom) values (next value for seq, 'Bloody Mary');
insert into cocktails (id, nom) values (next value for seq, 'Cuba libre');
insert into cocktails (id, nom) values (next value for seq, 'Americano');
insert into cocktails (id, nom) values (next value for seq, 'Daiquiri');
insert into cocktails (id, nom) values (next value for seq, 'Gin Fizz');
insert into cocktails (id, nom) values (next value for seq, 'Sangria');
insert into cocktails (id, nom) values (next value for seq, 'Ti’ punch');
insert into cocktails (id, nom) values (next value for seq, 'Long island Iced Tea');
insert into cocktails (id, nom) values (next value for seq, 'White Russian');
insert into cocktails (id, nom) values (next value for seq, 'Champagne cocktail');
insert into cocktails (id, nom) values (next value for seq, 'Blue Hawaiian');
insert into cocktails (id, nom) values (next value for seq, 'Russe Blanc');
insert into cocktails (id, nom) values (next value for seq, 'Gin Tonic');
insert into cocktails (id, nom) values (next value for seq, 'Black Russian');
insert into cocktails (id, nom) values (next value for seq, 'Pisco sour');
insert into cocktails (id, nom) values (next value for seq, 'Black Jack');
insert into cocktails (id, nom) values (next value for seq, 'Vin chaud');
insert into cocktails (id, nom) values (next value for seq, 'Screwdriver (Vodka orange)');
insert into cocktails (id, nom) values (next value for seq, 'Amaretto Sour');
insert into cocktails (id, nom) values (next value for seq, 'Pink lady');
insert into cocktails (id, nom) values (next value for seq, 'Rusty Nail');
insert into cocktails (id, nom) values (next value for seq, 'Negroni');
insert into cocktails (id, nom) values (next value for seq, 'Mimosa');
insert into cocktails (id, nom) values (next value for seq, 'Singapore Sling');
insert into cocktails (id, nom) values (next value for seq, 'White Lady');
insert into cocktails (id, nom) values (next value for seq, 'Tom Collins');
insert into cocktails (id, nom) values (next value for seq, 'Agua de valencia');
insert into cocktails (id, nom) values (next value for seq, 'Absinthe Cocktail');
insert into cocktails (id, nom) values (next value for seq, 'Bloody caesar');
insert into cocktails (id, nom) values (next value for seq, 'Alexandra');
insert into cocktails (id, nom) values (next value for seq, 'Barbotage');
insert into cocktails (id, nom) values (next value for seq, 'El Diablo');
insert into cocktails (id, nom) values (next value for seq, 'Old Fashioned');
insert into cocktails (id, nom) values (next value for seq, 'Hydromel');
insert into cocktails (id, nom) values (next value for seq, 'Side-car');
insert into cocktails (id, nom) values (next value for seq, 'Bleue');
insert into cocktails (id, nom) values (next value for seq, 'Bronx');
insert into cocktails (id, nom) values (next value for seq, 'Kir breton');
insert into cocktails (id, nom) values (next value for seq, 'Black Velvet');
insert into cocktails (id, nom) values (next value for seq, 'Daïquiri Floridita (Frozen Daïquiri)');
insert into cocktails (id, nom) values (next value for seq, 'Zizi coincoin');
insert into cocktails (id, nom) values (next value for seq, 'Jack rose');
insert into cocktails (id, nom) values (next value for seq, 'Hemingway Spécial');
insert into cocktails (id, nom) values (next value for seq, 'Balalaïka (Troïka)');
insert into cocktails (id, nom) values (next value for seq, 'Stinger');
insert into cocktails (id, nom) values (next value for seq, 'Godfather');
insert into cocktails (id, nom) values (next value for seq, 'Screaming orgasm');
insert into cocktails (id, nom) values (next value for seq, 'Pick me up');
insert into cocktails (id, nom) values (next value for seq, 'Red lion');
insert into cocktails (id, nom) values (next value for seq, 'Apple jack (Applejack)');
insert into cocktails (id, nom) values (next value for seq, 'Saudade');
insert into cocktails (id, nom) values (next value for seq, '42nd Street');
insert into cocktails (id, nom) values (next value for seq, 'Porto flip');
insert into cocktails (id, nom) values (next value for seq, 'Coco Cup');
insert into cocktails (id, nom) values (next value for seq, 'Alaska');
insert into cocktails (id, nom) values (next value for seq, 'Orange blossom');
insert into cocktails (id, nom) values (next value for seq, 'Brandy Alexander');
insert into cocktails (id, nom) values (next value for seq, 'Angel’s Kiss');
insert into cocktails (id, nom) values (next value for seq, 'Algonquin');
insert into cocktails (id, nom) values (next value for seq, 'Fun at the beach');
insert into cocktails (id, nom) values (next value for seq, 'Macca');
insert into cocktails (id, nom) values (next value for seq, 'Garibaldi');
insert into cocktails (id, nom) values (next value for seq, 'Apple pekin');
insert into cocktails (id, nom) values (next value for seq, 'Gimlet');
insert into cocktails (id, nom) values (next value for seq, 'Harvey Wallbanger');
insert into cocktails (id, nom) values (next value for seq, 'Amer Picon Cocktail');
insert into cocktails (id, nom) values (next value for seq, 'Nuit de noces');
insert into cocktails (id, nom) values (next value for seq, 'Godmother');
insert into cocktails (id, nom) values (next value for seq, 'Banana bliss');
insert into cocktails (id, nom) values (next value for seq, 'Brandy egg-nog');
insert into cocktails (id, nom) values (next value for seq, 'Vieux carré');
insert into cocktails (id, nom) values (next value for seq, 'Golden Dream');
insert into cocktails (id, nom) values (next value for seq, 'Scotch sour');
insert into cocktails (id, nom) values (next value for seq, 'Sazerac');
insert into cocktails (id, nom) values (next value for seq, 'Silver Fizz');
insert into cocktails (id, nom) values (next value for seq, 'Bull Shot');
insert into cocktails (id, nom) values (next value for seq, 'Pink gin');
insert into cocktails (id, nom) values (next value for seq, 'Cathedrale');
insert into cocktails (id, nom) values (next value for seq, 'Brooklyn');
insert into cocktails (id, nom) values (next value for seq, 'Bitters Highball');
insert into cocktails (id, nom) values (next value for seq, 'Brandy Flip');
insert into cocktails (id, nom) values (next value for seq, 'Golden Cadillac');
insert into cocktails (id, nom) values (next value for seq, 'Bossom caresser (Bosom caresser)');
insert into cocktails (id, nom) values (next value for seq, 'Pictonic');
insert into cocktails (id, nom) values (next value for seq, 'Boulevardier');
insert into cocktails (id, nom) values (next value for seq, 'Clover Club');
insert into cocktails (id, nom) values (next value for seq, 'Margot');
insert into cocktails (id, nom) values (next value for seq, 'Sling');
insert into cocktails (id, nom) values (next value for seq, 'Champagne cocktail');