-- https://www.mockaroo.com/
insert into clients (id, nom, email, date_naissance, titre) values (next value for seq, 'Wanda Gray', 'wgray0@ebay.co.uk', date '1988-07-26', 2);
insert into clients (id, nom, email, date_naissance, titre) values (next value for seq, 'Lisa Mcdonald', 'lmcdonald1@de.vu', date '1952-06-04', 2);
insert into clients (id, nom, email, date_naissance, titre) values (next value for seq, 'Barbara Kim', 'bkim2@deviantart.com', date '1958-07-31', 2);
insert into clients (id, nom, email, date_naissance, titre) values (next value for seq, 'Kevin Sims', 'ksims3@usatoday.com', date '1986-06-03', 1);
insert into clients (id, nom, email, date_naissance, titre) values (next value for seq, 'Phyllis Johnson', 'pjohnson4@ovh.net', date '1980-10-07', 2);
insert into clients (id, nom, email, date_naissance, titre) values (next value for seq, 'Annie Gutierrez', 'agutierrez5@msu.edu', date '1954-02-02', 2);
insert into clients (id, nom, email, date_naissance, titre) values (next value for seq, 'William Day', 'wday6@squarespace.com', date '1960-05-15', 1);
insert into clients (id, nom, email, date_naissance, titre) values (next value for seq, 'Cheryl Woods', 'cwoods7@storify.com', date '1981-04-08', 2);
insert into clients (id, nom, email, date_naissance, titre) values (next value for seq, 'Richard Cox', 'rcox8@dailymotion.com', date '1996-04-25', 1);
insert into clients (id, nom, email, date_naissance, titre) values (next value for seq, 'Bobby Morris', 'bmorris9@intel.com', date '1990-03-30', 1);

insert into roles (id, libelle) values (1, 'Serveur');
insert into roles (id, libelle) values (2, 'Responsable');

insert into employes (id, nom, idrole) values (1, 'Katherine Peters', 1);
insert into employes (id, nom, idrole) values (2, 'Jimmy Simmons', 1);
insert into employes (id, nom, idrole) values (3, 'Annie Diaz', 2);

insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Mojito', 'MOJITO', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Piña Colada', 'PINA COLADA', '11')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Margarita', 'MARGARITA', '9')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Sex on the beach', 'SEX ON THE BEACH', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Caipirinha', 'CAIPIRINHA', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Cosmopolitan', 'COSMOPOLITAN', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Blue Lagoon', 'BLUE LAGOON', '11')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Tequila Sunrise', 'TEQUILA SUNRISE', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Punch', 'PUNCH', '9')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Bloody Mary', 'BLOODY MARY', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Cuba libre', 'CUBA LIBRE', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Americano', 'AMERICANO', '11')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Daiquiri', 'DAIQUIRI', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Gin Fizz', 'GIN FIZZ', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Sangria', 'SANGRIA', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Ti’ punch', 'TI PUNCH', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Long island Iced Tea', 'LONG ISLAND ICED TEA', '11')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'White Russian', 'WHITE RUSSIAN', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Champagne cocktail', 'CHAMPAGNE COCKTAIL', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Blue Hawaiian', 'BLUE HAWAIIAN', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Russe Blanc', 'RUSSE BLANC', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Gin Tonic', 'GIN TONIC', '11')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Black Russian', 'BLACK RUSSIAN', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Pisco sour', 'PISCO SOUR', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Black Jack', 'BLACK JACK', '11')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Vin chaud', 'VIN CHAUD', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Screwdriver (Vodka orange)', 'SCREWDRIVER VODKA ORANGE', '9')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Amaretto Sour', 'AMARETTO SOUR', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Pink lady', 'PINK LADY', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Rusty Nail', 'RUSTY NAIL', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Negroni', 'NEGRONI', '11')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Mimosa', 'MIMOSA', '9')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Singapore Sling', 'SINGAPORE SLING', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'White Lady', 'WHITE LADY', '9')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Tom Collins', 'TOM COLLINS', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Agua de valencia', 'AGUA DE VALENCIA', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Absinthe Cocktail', 'ABSINTHE COCKTAIL', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Bloody caesar', 'BLOODY CAESAR', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Alexandra', 'ALEXANDRA', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Barbotage', 'BARBOTAGE', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'El Diablo', 'EL DIABLO', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Old Fashioned', 'OLD FASHIONED', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Hydromel', 'HYDROMEL', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Side-car', 'SIDECAR', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Bleue', 'BLEUE', '11')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Bronx', 'BRONX', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Kir breton', 'KIR BRETON', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Black Velvet', 'BLACK VELVET', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Daïquiri Floridita (Frozen Daïquiri)', 'DAIQUIRI FLORIDITA FROZEN DAIQUIRI', '11')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Zizi coincoin', 'ZIZI COINCOIN', '11')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Jack rose', 'JACK ROSE', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Hemingway Spécial', 'HEMINGWAY SPECIAL', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Balalaïka (Troïka)', 'BALALAIKA TROIKA', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Stinger', 'STINGER', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Godfather', 'GODFATHER', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Screaming orgasm', 'SCREAMING ORGASM', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Pick me up', 'PICK ME UP', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Red lion', 'RED LION', '11')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Apple jack (Applejack)', 'APPLE JACK APPLEJACK', '9')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Saudade', 'SAUDADE', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, '42nd Street', '42ND STREET', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Porto flip', 'PORTO FLIP', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Coco Cup', 'COCO CUP', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Alaska', 'ALASKA', '9')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Orange blossom', 'ORANGE BLOSSOM', '11')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Brandy Alexander', 'BRANDY ALEXANDER', '11')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Angel’s Kiss', 'ANGELS KISS', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Algonquin', 'ALGONQUIN', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Fun at the beach', 'FUN AT THE BEACH', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Macca', 'MACCA', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Garibaldi', 'GARIBALDI', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Apple pekin', 'APPLE PEKIN', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Gimlet', 'GIMLET', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Harvey Wallbanger', 'HARVEY WALLBANGER', '9')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Amer Picon Cocktail', 'AMER PICON COCKTAIL', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Nuit de noces', 'NUIT DE NOCES', '11')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Godmother', 'GODMOTHER', '11')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Banana bliss', 'BANANA BLISS', '9')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Brandy egg-nog', 'BRANDY EGGNOG', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Vieux carré', 'VIEUX CARRE', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Golden Dream', 'GOLDEN DREAM', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Scotch sour', 'SCOTCH SOUR', '11')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Sazerac', 'SAZERAC', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Silver Fizz', 'SILVER FIZZ', '11')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Bull Shot', 'BULL SHOT', '11')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Pink gin', 'PINK GIN', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Cathedrale', 'CATHEDRALE', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Brooklyn', 'BROOKLYN', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Bitters Highball', 'BITTERS HIGHBALL', '9')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Brandy Flip', 'BRANDY FLIP', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Golden Cadillac', 'GOLDEN CADILLAC', '9')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Bossom caresser (Bosom caresser)', 'BOSSOM CARESSER BOSOM CARESSER', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Pictonic', 'PICTONIC', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Boulevardier', 'BOULEVARDIER', '12')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Clover Club', 'CLOVER CLUB', '9')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Margot', 'MARGOT', '10')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Sling', 'SLING', '8')
insert into cocktails (id, nom, norm, prix) values (next value for seq, 'Champagne cocktail', 'CHAMPAGNE COCKTAIL', '11')
